name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Fix asset paths
        run: |
          # Check what's in the output directory
          ls -la out/
          echo "--- Contents of out directory ---"
          find out/ -type d -name "*" | head -20
          echo "--- Looking for assets directory ---"
          find out/ -name "assets" -type d
          echo "--- Looking for _next directory ---"
          find out/ -name "_next" -type d
          
          # Copy assets to root for GitHub Pages compatibility
          cd out
          if [ -d "zeeautotryes-website/assets" ]; then
            cp -r zeeautotryes-website/assets ./
            echo "Copied assets directory"
          else
            echo "zeeautotryes-website/assets not found, checking for assets in root"
            if [ -d "assets" ]; then
              echo "Assets already in root directory"
            else
              echo "No assets directory found"
            fi
          fi
          
          if [ -d "zeeautotryes-website/_next" ]; then
            cp -r zeeautotryes-website/_next ./
            echo "Copied _next directory"
          else
            echo "zeeautotryes-website/_next not found, checking for _next in root"
            if [ -d "_next" ]; then
              echo "_next already in root directory"
            else
              echo "No _next directory found"
            fi
          fi
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
