name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Prepare for GitHub Pages subdirectory
        run: |
          # Create the subdirectory structure for GitHub Pages
          mkdir -p out/zeeautotryes-website
          
          # Move all built files to the subdirectory
          cd out
          mv *.html zeeautotryes-website/ 2>/dev/null || true
          mv *.txt zeeautotryes-website/ 2>/dev/null || true
          mv service zeeautotryes-website/ 2>/dev/null || true
          mv home2 zeeautotryes-website/ 2>/dev/null || true
          mv about zeeautotryes-website/ 2>/dev/null || true
          mv contact zeeautotryes-website/ 2>/dev/null || true
          mv project zeeautotryes-website/ 2>/dev/null || true
          mv team zeeautotryes-website/ 2>/dev/null || true
          mv blog zeeautotryes-website/ 2>/dev/null || true
          mv _next zeeautotryes-website/ 2>/dev/null || true
          mv assets zeeautotryes-website/ 2>/dev/null || true
          
          # Create a root index.html that redirects to the subdirectory
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=/zeeautotryes-website/">
            <link rel="canonical" href="/zeeautotryes-website/">
          </head>
          <body>
            <p>Redirecting to <a href="/zeeautotryes-website/">zeeautotryes-website</a>...</p>
          </body>
          </html>
          EOF
          
          echo "Created subdirectory structure for GitHub Pages"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
