name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Fix static asset paths
        run: |
          # Fix image paths in ALL HTML files to include basePath
          echo "Fixing static asset paths in all HTML files..."
          
          # Find and fix all HTML files recursively
          find out/ -name "*.html" -type f | while read file; do
            echo "Processing: $file"
            sed -i 's|src="/assets/|src="/zeeautotryes-website/assets/|g' "$file"
            sed -i 's|href="/assets/|href="/zeeautotryes-website/assets/|g' "$file"
            sed -i 's|data-src="/assets/|data-src="/zeeautotryes-website/assets/|g' "$file"
            sed -i 's|data-background="/assets/|data-background="/zeeautotryes-website/assets/|g' "$file"
            sed -i 's|url("/assets/|url("/zeeautotryes-website/assets/|g' "$file"
            sed -i 's|url(/assets/|url(/zeeautotryes-website/assets/|g' "$file"
          done
          
          # Also fix any CSS files that might contain asset references
          find out/ -name "*.css" -type f | while read file; do
            echo "Processing CSS: $file"
            sed -i 's|url("/assets/|url("/zeeautotryes-website/assets/|g' "$file"
            sed -i 's|url(/assets/|url(/zeeautotryes-website/assets/|g' "$file"
          done
          
          echo "Fixed static asset paths in all files"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
